# Inspired by https://blog.frankel.ch/github-actions-maven-releases/ (kudos)
# see https://gist.github.com/sualeh/ae78dc16123899d7942bc38baba5203c
# how to use github and central server credentials?

name: Release

on:
  workflow_dispatch:
        

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Setup For Github
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
          cache: maven
          server-id: github
          
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          
      - name: Prepare Release
        run: mvn -B release:prepare
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Rollback
        if: failure()
        run: mvn -B release:rollback
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        
          
      - name: Setup For Central
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
          cache: maven
          server-id: ossrh
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}    
          
      - name: release to central
        run: mvn release:perform --file pom.xml --batch-mode -P distribution
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
